global.recipes_witcher_alchemy_data = json_decode(@'{
    "hanged_man_venom": {
        "CAT":      "weapon_oil",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "oil",
        "Recipe3":  "stool",
        "Recipe4":  "henbane",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Book"
    },
    "vampire_oil": {
        "CAT":      "weapon_oil",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "oil",
        "Recipe3":  "garlic",
        "Recipe4":  "hemp",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Book"
    },
    "necrophage_oil": {
        "CAT":      "weapon_oil",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "oil",
        "Recipe3":  "mindwort",
        "Recipe4":  "lavender",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Book"
    },
    "specter_oil": {
        "CAT":      "weapon_oil",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "oil",
        "Recipe3":  "skull",
        "Recipe4":  "horsetail",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Book"
    },
    "insectoid_oil": {
        "CAT":      "weapon_oil",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "oil",
        "Recipe3":  "flyagaric",
        "Recipe4":  "henbane",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Book"
    },
    "hybrid_oil": {
        "CAT":      "weapon_oil",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "oil",
        "Recipe3":  "flyagaric",
        "Recipe4":  "stool",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Book"
    },
    "ogroid_oil": {
        "CAT":      "weapon_oil",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "oil",
        "Recipe3":  "ginger",
        "Recipe4":  "henbane",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Book"
    },
    "thunderbolt_potion": {
        "CAT":      "witcher_potion",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "henbane",
        "Recipe4":  "henbane",
        "Recipe5":  "hemp",
        "Recipe6":  "-",
        "ADDITIVES": "hop, rotbloom",
        "AMOUNT":   "2",
        "XP":       "25",
        "SOURCE":   "Book"
    },
    "blizzard_potion": {
        "CAT":      "witcher_potion",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "peppermint",
        "Recipe4":  "rhubarb",
        "Recipe5":  "mindwort",
        "Recipe6":  "-",
        "ADDITIVES": "hornet_honey, bear_fat, truffle",
        "AMOUNT":   "2",
        "XP":       "25",
        "SOURCE":   "Book"
    },
    "petri_philter": {
        "CAT":      "witcher_potion",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "mindwort",
        "Recipe4":  "agrimony",
        "Recipe5":  "agrimony",
        "Recipe6":  "-",
        "ADDITIVES": "moose_kidney, azurecap",
        "AMOUNT":   "2",
        "XP":       "25",
        "SOURCE":   "Book"
    },
    "swallow_potion": {
        "CAT":      "witcher_potion",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "fleawort",
        "Recipe4":  "bogbean",
        "Recipe5":  "wormwood",
        "Recipe6":  "-",
        "ADDITIVES": "hyssop, spleenwort",
        "AMOUNT":   "2",
        "XP":       "25",
        "SOURCE":   "Book"
    },
    "tawny_owl": {
        "CAT":      "witcher_potion",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "peppermint",
        "Recipe4":  "thyme",
        "Recipe5":  "thyme",
        "Recipe6":  "-",
        "ADDITIVES": "silverleaf, azurecap",
        "AMOUNT":   "2",
        "XP":       "25",
        "SOURCE":   "Book"
    },
    "golden_oriole": {
        "CAT":      "witcher_potion",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "poppy",
        "Recipe4":  "burdock",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "ADDITIVES": "spidervine, puffball, dragonfruit",
        "AMOUNT":   "2",
        "XP":       "25",
        "SOURCE":   "Book"
    },
    "ghoul_decoction": {
        "CAT":      "witcher_decoction",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "ghoul_heart",
        "Recipe4":  "burdock, bogbean, burnet",
        "Recipe5":  "pennybun",
        "Recipe6":  "pennybun",
        "AMOUNT":   "1",
        "XP":       "50",
        "SOURCE":   "Book"
    },
    "crawler_decoction": {
        "CAT":      "witcher_decoction",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "spider_eye, mandibles",
        "Recipe4":  "henbane",
        "Recipe5":  "henbane",
        "Recipe6":  "flyagaric",
        "AMOUNT":   "1",
        "XP":       "50",
        "SOURCE":   "Book"
    },
    "harpy_decoction": {
        "CAT":      "witcher_decoction",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "harpy_egg_raw, harpy_stomach",
        "Recipe4":  "ginger",
        "Recipe5":  "poppy",
        "Recipe6":  "poppy",
        "AMOUNT":   "1",
        "XP":       "50",
        "SOURCE":   "Book"
    },
    "troll_decoction": {
        "CAT":      "witcher_decoction",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "troll_gland, tusks_troll",
        "Recipe4":  "burdock",
        "Recipe5":  "peppermint",
        "Recipe6":  "mindwort",
        "AMOUNT":   "1",
        "XP":       "50",
        "SOURCE":   "Book"
    },
    "gulon_decoction": {
        "CAT":      "witcher_decoction",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "alcohol_essentia",
        "Recipe3":  "gulon_liver",
        "Recipe4":  "henbane",
        "Recipe5":  "nettle",
        "Recipe6":  "rhubarb",
        "AMOUNT":   "1",
        "XP":       "50",
        "SOURCE":   "Book"
    },
    "oil": {
        "CAT":      "other",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "-",
        "Recipe3":  "-",
        "Recipe4":  "-",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "ADDITIVES": "lentils, meat_fat_raw",
        "AMOUNT":   "1",
        "XP":       "5",
        "SOURCE":   "Base Recipe"
    },
    "alcohol_essentia": {
        "CAT":      "other",
        "Recipe1":  "alchemy_workbench, caravan_alchemy",
        "Recipe2":  "-",
        "Recipe3":  "-",
        "Recipe4":  "-",
        "Recipe5":  "-",
        "Recipe6":  "-",
        "AMOUNT":   "1",
        "XP":       "10",
        "SOURCE":   "Base Recipe"
    }
}')

global.recipes_witcher_alchemy_categories_order_list = __dsDebuggerListCreate()
ds_list_add(global.recipes_witcher_alchemy_categories_order_list, "weapon_oil", "witcher_potion", "witcher_decoction", "other")

global.recipes_witcher_alchemy_category_order_map = json_decode(@'{
    "weapon_oil": ["hanged_man_venom", "vampire_oil", "necrophage_oil", "specter_oil", "insectoid_oil", "hybrid_oil", "ogroid_oil"],
    "witcher_potion": ["thunderbolt_potion", "blizzard_potion", "petri_philter", "swallow_potion", "tawny_owl", "golden_oriole"],
    "witcher_decoction": ["ghoul_decoction", "crawler_decoction", "harpy_decoction", "troll_decoction", "gulon_decoction"],
    "other": ["oil", "alcohol_essentia"]
}')
